# -*- coding: utf-8 -*-
"""Regex-pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Zxq2HaqwgESSluWVcOGzcS65lqQOC-c
"""

#Write the following functions and use “re” to get the solution
#1.	Write a function named “LoveForFrenchFries” which takes in a string and returns the number of times the word ”potato” is in the given string.
#Example:
#LoveForFrenchFries(“potato”)-> 1
#LoveForFrenchFries(“potatopotato”) ->2
#Note: Let the input string be of  continuous letters like the above examples.

import re

def LoveForFrenchFries(string):
  pattern=r'potato'
  result=re.findall(pattern,string)
  count=0
  for i in result:
    if i=="potato":
     count=count+1
    else:
     count=count
  return count

LoveForFrenchFries(input("enter a string 1  : "))

#2.	Write a function called “LinkVowels” which takes a string and returns True if one word ends with a vowel and the adjacent starts with a vowel.

#Example:
#LinkVowels(“code all functions”)->True ( “code” ends with vowel and “all” starts with vowel)
#LinkVowels(“ These are crazy ones”)-> True (“These” ends with vowel and “are” starts with a vowel)
#LinkVowels(“This sucks”)-> False

import re

def LinkVowels(string):
   pattern=r'\b\w+[aeiouAEIOU]\b\s\b[aeiouAEIOU]\w+\b'
   result=re.search(pattern,string)
   if result:
     return True
   else:
     return False

LinkVowels(input("enter a string 2 : "))

